/**
 * Bake the brand fonts into the source tree.
 *
 * A chart's layout is measured from its text, so the renderer cannot start
 * until the real fonts are available. Fetching them at render time makes the
 * output depend on the network — the same chart comes out differently offline,
 * in CI, or when Google Fonts is slow. Embedding removes the variable.
 *
 * Run this only when the brand fonts change:
 *   node packages/core/scripts/fetch-fonts.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const CHROME_UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36';

// Weight *ranges*, not individual weights. Asking for two weights of a variable
// font returns the whole variable font twice — Source Serif 4 alone came to
// 239 kB that way, for one typeface.
//
// Every family any scene names first. Source Serif 4 and JetBrains Mono were
// missing: the Manim scene — the default — sets its titles in the serif and its
// compartment rows in the mono, so without them layout was measured against
// whatever serif and monospace the render host happened to have. The same chart
// came out differently on a different machine, which is the exact failure
// embedding exists to prevent.
const QUERY =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@400..700&family=Lato:wght@400;700' +
  '&family=Source+Serif+4:opsz,wght@8..60,400..600&family=JetBrains+Mono:wght@400..500&display=swap';

const css = await (await fetch(QUERY, { headers: { 'User-Agent': CHROME_UA } })).text();

// Only the latin subset: it covers the Roman alphabet at a fraction of the size,
// and diagram labels outside it fall back to the system stack.
const faces = [];
for (const [, subset, body] of css.matchAll(/\/\*\s*([\w[\]-]+)\s*\*\/\s*@font-face\s*\{(.*?)\}/gs)) {
  if (subset !== 'latin') continue;
  const family = /font-family:\s*'([^']+)'/.exec(body)[1];
  const weight = /font-weight:\s*([^;]+);/.exec(body)[1].trim();
  const style = /font-style:\s*([^;]+);/.exec(body)?.[1].trim() ?? 'normal';
  const url = /url\((https[^)]+)\)/.exec(body)[1];
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  faces.push({ family, weight, style, base64: bytes.toString('base64'), bytes: bytes.length });
  process.stderr.write(`  ${family} ${weight}  ${(bytes.length / 1024).toFixed(1)} kB\n`);
}

const total = faces.reduce((sum, f) => sum + f.bytes, 0);
process.stderr.write(`  total ${(total / 1024).toFixed(1)} kB\n`);

const body = faces
  .map(
    (f) => `@font-face{font-family:'${f.family}';font-style:${f.style};font-weight:${f.weight};` +
      `font-display:block;src:url(data:font/woff2;base64,${f.base64}) format('woff2')}`,
  )
  .join('\n');

writeFileSync(
  join(here, '..', 'src', 'font-data.ts'),
  `// Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `// ${[...new Set(faces.map((f) => f.family))].join(', ')}; latin subset, ` +
    `${(total / 1024).toFixed(0)} kB total.\n` +
    `export const fontFaceCss = \`${body}\`;\n`,
);
process.stderr.write('wrote src/font-data.ts\n');
