import { scopeCss } from './scope.ts';

/**
 * Emit a chart as a standalone React component.
 *
 * The diagram is already drawn by the time this runs, so the component carries
 * no dependency on this package, no mermaid, no ELK and no client JavaScript —
 * which also means it renders inside a Server Component and costs a page
 * nothing at runtime. Regenerate the file to change the diagram.
 */

export interface ReactComponentInput {
  /** PascalCase component name. */
  name: string;
  svg: string;
  css: string;
  /** What a screen reader announces. */
  summary: string;
  /** Provenance, written into the header comment. */
  source?: string;
  meta?: string;
  /** Emit plain JavaScript instead of TypeScript. */
  javascript?: boolean;
  /** True when the chart takes its typefaces from the page it lands in. */
  inherited?: boolean;
  /** The stack the layout was measured against. */
  measuredWith?: string;
}

/** `cohort-funnel` or `cohort_funnel.tsx` becomes `CohortFunnel`. */
export function componentName(fileName: string): string {
  const base =
    fileName
      .replace(/\.[^.]+$/, '')
      .split(/[\\/]/)
      .pop() ?? 'Chart';
  const parts = base.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const name = parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join('');
  // A React component must start with a capital letter, and an identifier
  // cannot start with a digit — `2024-roadmap.mmd` would otherwise emit a file
  // that does not parse.
  return /^[A-Za-z]/.test(name) ? name : `Chart${name}`;
}

/** A CSS identifier derived from the component name, for scoping. */
const rootId = (name: string) => `gc-${name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}`;

/**
 * Quote a string for a template literal.
 *
 * The markup is emitted as one literal rather than as JSX. Translating it into
 * JSX would mean hand-mapping every attribute the renderer emits — `class`,
 * `stroke-width`, `text-anchor`, `clip-path`, CSS custom properties in `style` —
 * and every one of those is a chance for the component to differ from the SVG
 * the tests actually check. Keeping the bytes identical removes the whole class
 * of problem.
 */
function literal(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

export function reactComponent(input: ReactComponentInput): string {
  const { name, summary, javascript = false } = input;
  const id = rootId(name);
  const markup = `<style>${scopeCss(input.css, id)}</style>${input.svg}`;
  const ts = !javascript;

  const props = ts
    ? `\nexport interface ${name}Props {\n` +
      `  /** Placed on the wrapper, so the page can size and position the chart. */\n` +
      `  className?: string;\n` +
      `  /** Overrides what a screen reader announces. */\n` +
      `  label?: string;\n` +
      `}\n`
    : '';

  const signature = ts
    ? `{ className, label = DESCRIPTION }: ${name}Props`
    : '{ className, label = DESCRIPTION }';

  return `${header(input, id)}
const DESCRIPTION = ${JSON.stringify(summary)};

const MARKUP = \`${literal(markup)}\`;
${props}
export function ${name}(${signature}) {
  return (
    <div
      id=${JSON.stringify(id)}
      className={className}
      role="img"
      aria-label={label}
      dangerouslySetInnerHTML={{ __html: MARKUP }}
    />
  );
}

export default ${name};
`;
}

/**
 * Say which font case this component is in, because the two have opposite
 * obligations and getting the wrong one produces boxes that do not fit.
 */
function fontNote(input: ReactComponentInput): string[] {
  if (!input.inherited) {
    return [
      'FONTS: this diagram was drawn in its own typefaces. Render',
      '<GeekchartFonts /> once at the root of the app, or import',
      '@geekchart/react/fonts.css, or the labels will not fit their boxes.',
    ];
  }
  return [
    'FONTS: inherited from the page — nothing to ship, and the chart matches the',
    'text around it.',
    '',
    `Its boxes were sized against ${input.measuredWith ?? 'a neutral system stack'}.`,
    'That only has to be close, not exact; a very different face (a monospace',
    'where a narrow sans was measured) will leave labels sitting loose in their',
    'outlines or pressed against them. Regenerate with --measure-with set to this',
    'page’s own stack if that happens.',
  ];
}

function header(input: ReactComponentInput, id: string): string {
  const lines = [
    'Generated by geekchart — do not edit by hand.',
    ...(input.source ? [`Source: ${input.source}`] : []),
    ...(input.meta ? [input.meta] : []),
    '',
    'Self-contained: no dependencies, no client JavaScript, and safe inside a',
    'React Server Component. The animation is CSS and already hides itself behind',
    'prefers-reduced-motion, so a viewer who asks for less motion sees the',
    'finished diagram rather than a blank frame.',
    '',
    `Every selector is scoped to #${id}, so two charts on one page cannot`,
    'overwrite each other’s styles or animations.',
    '',
    ...fontNote(input),
  ];
  return `/**\n${lines.map((l) => (l ? ` * ${l}` : ' *')).join('\n')}\n */`;
}
