import * as fontkit from 'fontkit';
import { fontFaceCss } from '../font-data.ts';
import type { Measurer } from '../layout/measure.ts';

/**
 * Text measurement without a browser.
 *
 * `makeMeasurer` in `../layout/measure.ts` answers "how wide is this string"
 * by mounting a hidden SVG `<text>` and calling `getBBox()`. That needs a
 * DOM. This answers the same question from the font files themselves:
 * `font-data.ts` embeds Archivo, JetBrains Mono, Lato and Source Serif 4 as
 * base64 WOFF2, which fontkit can open directly — no separate WOFF2 decoder
 * needed, confirmed against the real embedded data — and `Font#layout()`
 * shapes a string with real GPOS kerning, not just a sum of independent
 * advance widths.
 *
 * Two measured caveats, from running `packages/cli/scripts/spike-node.mjs`
 * against the six comparison fixtures:
 *
 * 1. Archivo's embedded file is a variable font whose own `fvar` default is
 *    weight 600 (SemiBold) — not 400, which is what the browser actually
 *    renders at when nothing sets `font-weight`. `regularFace` below reads
 *    the file's un-instanced default, so Archivo-set text measures ~6%
 *    wider here than in the browser. Re-instancing to 400 with fontkit's own
 *    `Font#getVariation()` was tried and rejected: on this embedded,
 *    subsetted file it breaks the instanced font's `cmap` lookup (a fontkit
 *    2.0.4 issue), so it cannot resolve glyphs by code point at all.
 * 2. JetBrains Mono's default instance genuinely is weight 400, matching the
 *    browser, and its `hmtx` table is uniform (600/1000 em per glyph) — but
 *    Chromium still renders each glyph a hair wider (`getComputedTextLength`
 *    measured 7px where the raw table says 6.6px at 11px), consistent with
 *    the rasterizer rounding advances to whole device pixels at small sizes.
 *    Nothing here can reproduce that without emulating the browser's hinting.
 *
 * Both are small per-character effects that compound over a long label; see
 * the spike's `max Δtext`/`max Δbox` columns for how far they carry a real
 * chart's boxes from the browser's.
 *
 * Interface-compatible with `makeMeasurer`'s return value (`Measurer`), so
 * anywhere that takes one — `layout()`, `drawSequence`, `drawChronicle`, … —
 * takes this instead with no other change. `warnings` is extra: a caller that
 * wants to know about a missing-glyph fallback (see below) can read it after
 * calling `done()`; a caller that only wants the `Measurer` shape can ignore it.
 */

const GENERIC = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'ui-sans-serif',
  'ui-serif',
  'ui-monospace',
  'ui-rounded',
  'initial',
]);

interface EmbeddedFace {
  family: string;
  weightMin: number;
  weightMax: number;
  buffer: Buffer;
}

let embeddedFaces: EmbeddedFace[] | null = null;

/**
 * Every `@font-face` block in `font-data.ts`, decoded once.
 *
 * The CSS is generated by `scripts/fetch-fonts.mjs` and its shape has been
 * stable since — one block per family (or per static weight, for Lato, which
 * ships 400 and 700 as separate files rather than one variable font) — so a
 * single regex over the four fields this needs (family, weight range, format,
 * payload) is simpler than a real CSS parser for a file nothing else writes.
 */
function parseEmbeddedFaces(): EmbeddedFace[] {
  if (embeddedFaces) return embeddedFaces;
  const re =
    /font-family:'([^']+)';font-style:normal;font-weight:(\d+)(?:\s+(\d+))?;font-display:\w+;src:url\(data:font\/(\w+);base64,([^)]+)\)/g;
  const out: EmbeddedFace[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(fontFaceCss))) {
    const [, family, w1, w2, , b64] = m;
    if (!family || !w1 || !b64) continue;
    out.push({
      family,
      weightMin: Number(w1),
      weightMax: w2 ? Number(w2) : Number(w1),
      buffer: Buffer.from(b64, 'base64'),
    });
  }
  embeddedFaces = out;
  return out;
}

const fontCache = new Map<string, fontkit.Font | null>();

/**
 * The face a plain, unweighted `font-family: X` resolves to.
 *
 * The browser measurer never sets `font-weight` on its measuring element
 * (`makeMeasurer` only ever sets `fontFamily`, `fontSize`, `letterSpacing`),
 * so every measurement — even a bold title — happens at the browser's normal
 * weight, 400. That is a real quirk of the existing measurer, not something
 * to fix here: matching it is the point. For a variable face (Archivo,
 * JetBrains Mono, Source Serif 4, each shipped as one file spanning a weight
 * range) that means the face's default instance, which for all three here has
 * a 400 floor. Lato ships two separate static files; picking the one whose
 * own weight is exactly 400 gets the same answer by construction.
 */
function regularFace(familyLower: string): fontkit.Font | null {
  if (fontCache.has(familyLower)) return fontCache.get(familyLower)!;
  const candidate = parseEmbeddedFaces().find(
    (f) => f.family.toLowerCase() === familyLower && f.weightMin === 400,
  );
  let font: fontkit.Font | null = null;
  if (candidate) {
    const opened = fontkit.create(candidate.buffer);
    // Every embedded file is a single font, never a TTC — `create` returns a
    // plain `Font` for these, but the type is `Font | FontCollection`.
    font = 'layout' in opened ? opened : null;
  }
  fontCache.set(familyLower, font);
  return font;
}

/**
 * Pick the first family in a CSS `font-family` stack that we actually have a
 * file for — the same "first that resolves" rule a browser applies, except a
 * browser can fall back to whatever else is installed on the machine and this
 * can only fall back to the four embedded families. `'inherit'` — a role a
 * scene can set literally, meaning "whatever the host page uses" — resolves
 * against `measureWith` instead, the same stack `makeMeasurer`'s hidden host
 * sets `fontFamily` to for the same reason.
 */
function resolveFamily(stack: string, measureWith: string | undefined, warn: (m: string) => void): fontkit.Font {
  const tokens = stack
    .split(',')
    .map((t) => t.trim().replace(/^["']|["']$/g, ''))
    .filter(Boolean);
  for (const token of tokens) {
    if (token.toLowerCase() === 'inherit') {
      if (measureWith) return resolveFamily(measureWith, undefined, warn);
      continue;
    }
    if (GENERIC.has(token.toLowerCase())) continue;
    const font = regularFace(token.toLowerCase());
    if (font) return font;
  }
  // Every scene ships a stack that leads with an embedded family, so this
  // only fires for a caller-supplied stack this measurer was never taught —
  // e.g. `fonts.measureWith` naming a system font. Archivo is the closest
  // thing this renderer has to a body face, so it is the least-wrong stand-in.
  warn(
    `No embedded font matched "${stack}" — measured with Archivo as a stand-in. ` +
      `Widths for this text may not match a browser that actually has one of these fonts installed.`,
  );
  const fallback = regularFace('archivo');
  if (!fallback) throw new Error('Archivo, the fallback face, failed to load from font-data.ts.');
  return fallback;
}

/** `letter-spacing` in px, at this font size. Mirrors what a browser resolves. */
function trackingPx(tracking: string, size: number): number {
  const t = tracking.trim();
  if (!t || t === 'normal') return 0;
  const m = /^(-?[\d.]+)(em|px)?$/.exec(t);
  if (!m || !m[1]) return 0;
  const value = Number(m[1]);
  if (Number.isNaN(value)) return 0;
  return m[2] === 'px' ? value : value * size; // unitless and `em` both scale with size here
}

/**
 * A font's average advance, for the one glyph in a string it has no outline
 * for. Sampled off the run of the western alphabet plus digits — the same
 * kind of text every scene actually measures — rather than every glyph in
 * the font, which would drag the average down with glyphs no label ever uses.
 */
const AVERAGE_SAMPLE = 'etaoinshrdluETAOINSHRDLU0123456789';
const averageAdvanceCache = new WeakMap<fontkit.Font, number>();
function averageAdvance(font: fontkit.Font): number {
  const cached = averageAdvanceCache.get(font);
  if (cached !== undefined) return cached;
  const glyphs = font.glyphsForString(AVERAGE_SAMPLE);
  const total = glyphs.reduce((sum, g) => sum + g.advanceWidth, 0);
  const avg = glyphs.length ? total / glyphs.length : font.unitsPerEm * 0.5;
  averageAdvanceCache.set(font, avg);
  return avg;
}

export function makeNodeMeasurer(measureWith?: string): Measurer & { warnings: string[] } {
  const warnings: string[] = [];
  const warn = (m: string) => {
    if (!warnings.includes(m)) warnings.push(m);
  };

  return {
    measure(value, font, size, tracking = 'normal') {
      // SVG text content is normalized before layout the same way CSS
      // `white-space: normal` normalizes any inline text — the XML/HTML
      // default every browser applies to a `<text>` node: leading and
      // trailing whitespace is dropped entirely, and interior runs collapse
      // to one space. `makeMeasurer`'s hidden `<text>` + `getBBox()`
      // measures whatever that normalization already left, because the
      // browser does it before `getBBox()` ever runs. fontkit has no such
      // rule; it shapes exactly the string it is given, whitespace and all.
      // Found on an ER record row ("string name  PK", a double space from
      // column padding in the source): browser measured "string name PK"
      // (98px, the trimmed, collapsed string), fontkit measured the literal
      // two spaces (105px) — confirmed against the real embedded fonts that
      // leading/trailing space is dropped outright, not just collapsed to
      // one ("  leading" and "leading" measured identically). Normalizing
      // here matches what the browser already did to the string before it
      // ever measured it.
      const text = (value ?? '').trim().replace(/\s+/g, ' ') || ' ';
      const face = resolveFamily(font, measureWith, warn);
      const run = face.layout(text);
      let widthPx = 0;
      for (let i = 0; i < run.glyphs.length; i++) {
        const glyph = run.glyphs[i];
        const position = run.positions[i];
        if (!glyph || !position) continue;
        let unitsAdvance: number;
        // `.notdef` is glyph id 0 by TrueType/OpenType convention — fontkit
        // substitutes it for any code point the font has no outline for.
        if (glyph.id === 0) {
          warn(
            `"${font}" has no glyph for at least one character in "${value}" — ` +
              `measured that character at the font's average advance instead.`,
          );
          unitsAdvance = averageAdvance(face);
        } else {
          unitsAdvance = position.xAdvance;
        }
        // Chromium positions each glyph on the whole-device-pixel grid at
        // these sizes — confirmed against the real embedded fonts with a
        // throwaway `<text>` probe: every glyph in an untracked run
        // (JetBrains Mono's uniform 6.6px advance, Archivo's per-glyph
        // 4-8px advances alike) comes back from `getComputedTextLength` as a
        // whole number that is that glyph's own raw advance rounded to the
        // nearest integer, not the sum rounded once at the end. Summing the
        // raw advance and rounding once, as this used to, left the JetBrains
        // Mono captions the largest single source of Node/browser drift (up
        // to 14 units on a long label).
        widthPx += Math.round((unitsAdvance / face.unitsPerEm) * size);
      }
      const chars = [...text].length;
      // `letter-spacing` changes which glyphs this adds tracking after. The
      // same probe, repeated with `letter-spacing` set, found Chromium adds
      // it after *every* glyph, including the last — not just between pairs
      // (`chars - 1`, this file's own first guess, and the usual mental
      // model for "space between characters"). Measured against a five-step
      // ramp of tracked runs, `chars` matched every step to within 0.03px;
      // `chars - 1` was still off by a whole tracking-width on the shortest.
      // Left uncaught, that shows up compounded: `gitgraph`'s tracked,
      // tightly-packed commit tags sum many short labels left to right, and
      // the missing tracking on each one added up to an 8-unit-tall wrong
      // viewBox before this was found.
      return widthPx + trackingPx(tracking, size) * chars;
    },
    done() {
      // Nothing to release — there is no host element, unlike `makeMeasurer`.
    },
    warnings,
  };
}
